import { drizzle } from "drizzle-orm/mysql2";
import { supplements } from "../drizzle/schema";

const db = drizzle(process.env.DATABASE_URL!);

const supplementData = [
  // ─── FOCUS & COGNITION ────────────────────────────────────────────────────
  {
    slug: "alpha-gpc",
    name: "Alpha-GPC",
    category: "Cholinergic",
    summary: "A highly bioavailable choline source that crosses the blood-brain barrier to boost acetylcholine levels, enhancing memory, focus, and mental clarity.",
    description: "Alpha-GPC (Alpha-glycerophosphocholine) is a natural choline compound found in the brain. It is one of the most effective choline donors available, rapidly delivering choline to the brain where it supports the synthesis of the neurotransmitter acetylcholine. Research shows it improves memory formation, learning speed, and overall cognitive performance. Athletes also use it for its ability to stimulate growth hormone release. It is a foundational nootropic recommended for most cognitive stacks.",
    dosageMin: 300, dosageMax: 600, dosageUnit: "mg",
    scoreEnergy: 4, scoreMood: 5, scoreMemory: 9, scoreFocus: 8, scoreCreativity: 6, scoreSleep: 2, scoreAnxiety: 2,
    affiliatePrimary: "https://nootropicsdepot.com/alpha-gpc-capsules/?rfsn=supplement-stacker", affiliatePrimaryLabel: "Nootropics Depot",
    affiliateSecondary: "https://www.iherb.com/c/alpha-gpc?rcode=NSTACKER", affiliateSecondaryLabel: "iHerb",
    affiliateAmazon: "https://www.amazon.com/s?k=alpha+gpc+supplement&tag=nootropicstk-20",
    safetyRating: "very_safe" as const, isPopular: true, isFeatured: true,
  },
  {
    slug: "lions-mane",
    name: "Lion's Mane Mushroom",
    category: "Adaptogen",
    summary: "A medicinal mushroom that stimulates Nerve Growth Factor (NGF) production, supporting neuroplasticity, memory, and long-term brain health.",
    description: "Hericium erinaceus (Lion's Mane) is a functional mushroom with remarkable neuroprotective and neuroregenerative properties. Its active compounds, hericenones and erinacines, stimulate the synthesis of Nerve Growth Factor (NGF), a protein critical for the growth and maintenance of neurons. Regular supplementation has been shown to improve mild cognitive impairment, reduce anxiety and depression, and support overall brain health. It is one of the few supplements with genuine long-term neuroplasticity benefits.",
    dosageMin: 500, dosageMax: 3000, dosageUnit: "mg",
    scoreEnergy: 3, scoreMood: 7, scoreMemory: 8, scoreFocus: 7, scoreCreativity: 8, scoreSleep: 4, scoreAnxiety: 6,
    affiliatePrimary: "https://neurohacker.com/shop/qualia-mushroom?rfsn=supplement-stacker", affiliatePrimaryLabel: "Neurohacker",
    affiliateSecondary: "https://us.foursigmatic.com/collections/lion-s-mane?aff=nootropicstacker", affiliateSecondaryLabel: "Four Sigmatic",
    affiliateAmazon: "https://www.amazon.com/s?k=lions+mane+mushroom+supplement&tag=nootropicstk-20",
    safetyRating: "very_safe" as const, isPopular: true, isFeatured: true,
  },
  {
    slug: "bacopa",
    name: "Bacopa Monnieri",
    category: "Adaptogen",
    summary: "An Ayurvedic herb that enhances memory consolidation and reduces anxiety through its active bacosides, with effects building over 4–8 weeks.",
    description: "Bacopa monnieri is one of the most well-researched nootropic herbs. Its active compounds, bacosides, enhance synaptic communication by supporting the repair of damaged neurons and improving signal transmission. Multiple clinical trials confirm its ability to improve memory acquisition and retention, reduce anxiety, and protect the brain from oxidative stress. Unlike many nootropics, Bacopa requires consistent daily use for 4–8 weeks before its full cognitive benefits manifest.",
    dosageMin: 300, dosageMax: 600, dosageUnit: "mg",
    scoreEnergy: 2, scoreMood: 6, scoreMemory: 9, scoreFocus: 7, scoreCreativity: 5, scoreSleep: 5, scoreAnxiety: 7,
    affiliatePrimary: "https://nootropicsdepot.com/bacopa-monnieri-capsules/?rfsn=supplement-stacker", affiliatePrimaryLabel: "Nootropics Depot",
    affiliateSecondary: "https://www.iherb.com/c/bacopa?rcode=NSTACKER", affiliateSecondaryLabel: "iHerb",
    affiliateAmazon: "https://www.amazon.com/s?k=bacopa+monnieri+supplement&tag=nootropicstk-20",
    safetyRating: "very_safe" as const, isPopular: true, isFeatured: false,
  },
  {
    slug: "l-theanine",
    name: "L-Theanine",
    category: "Amino Acid",
    summary: "A calming amino acid from green tea that promotes relaxed alertness and synergizes powerfully with caffeine to smooth out stimulant jitteriness.",
    description: "L-Theanine is an amino acid found almost exclusively in tea leaves. It promotes alpha brain wave activity, producing a state of calm, focused alertness without sedation. Its most famous application is the 2:1 L-Theanine to caffeine stack, which is one of the most well-studied nootropic combinations in existence. This pairing reduces caffeine-induced anxiety and jitteriness while amplifying its focus and energy benefits. L-Theanine is considered one of the safest and most universally beneficial nootropics available.",
    dosageMin: 100, dosageMax: 400, dosageUnit: "mg",
    scoreEnergy: 3, scoreMood: 7, scoreMemory: 5, scoreFocus: 8, scoreCreativity: 6, scoreSleep: 6, scoreAnxiety: 9,
    affiliatePrimary: "https://nootropicsdepot.com/l-theanine-capsules/?rfsn=supplement-stacker", affiliatePrimaryLabel: "Nootropics Depot",
    affiliateSecondary: "https://www.iherb.com/c/l-theanine?rcode=NSTACKER", affiliateSecondaryLabel: "iHerb",
    affiliateAmazon: "https://www.amazon.com/s?k=l-theanine+supplement&tag=nootropicstk-20",
    safetyRating: "very_safe" as const, isPopular: true, isFeatured: true,
  },
  {
    slug: "citicoline",
    name: "Citicoline (CDP-Choline)",
    category: "Cholinergic",
    summary: "A premium choline source that also boosts brain energy metabolism and dopamine receptor density, making it one of the most versatile nootropics.",
    description: "Citicoline (Cytidine diphosphocholine) is a naturally occurring compound that serves dual roles: it is a potent choline donor for acetylcholine synthesis AND a precursor to uridine, which supports dopamine receptor density and synaptic membrane health. Clinical research shows it improves attention, memory, and mental energy. It is the choline source of choice in premium stacks like Mind Lab Pro and Qualia Mind. Citicoline also has neuroprotective properties and may help with recovery from brain injury.",
    dosageMin: 250, dosageMax: 500, dosageUnit: "mg",
    scoreEnergy: 6, scoreMood: 6, scoreMemory: 9, scoreFocus: 9, scoreCreativity: 7, scoreSleep: 2, scoreAnxiety: 3,
    affiliatePrimary: "https://www.mindlabpro.com/?a_aid=nootropicstacker", affiliatePrimaryLabel: "Mind Lab Pro",
    affiliateSecondary: "https://nootropicsdepot.com/citicoline-capsules/?rfsn=supplement-stacker", affiliateSecondaryLabel: "Nootropics Depot",
    affiliateAmazon: "https://www.amazon.com/s?k=citicoline+cdp-choline&tag=nootropicstk-20",
    safetyRating: "very_safe" as const, isPopular: true, isFeatured: true,
  },
  {
    slug: "phosphatidylserine",
    name: "Phosphatidylserine",
    category: "Phospholipid",
    summary: "A phospholipid that forms a critical part of neuronal cell membranes, supporting memory, learning, and stress resilience with strong clinical backing.",
    description: "Phosphatidylserine (PS) is a phospholipid that constitutes a significant portion of the brain's cell membranes. It is critical for maintaining cellular function, facilitating communication between neurons, and supporting the metabolism of glucose in the brain. The FDA has authorized a qualified health claim for PS and cognitive dysfunction. Clinical trials demonstrate improvements in memory, learning, concentration, and mood. It also reduces cortisol levels, making it valuable for stress management and athletic recovery.",
    dosageMin: 100, dosageMax: 400, dosageUnit: "mg",
    scoreEnergy: 4, scoreMood: 6, scoreMemory: 8, scoreFocus: 7, scoreCreativity: 5, scoreSleep: 4, scoreAnxiety: 6,
    affiliatePrimary: "https://www.mindlabpro.com/?a_aid=nootropicstacker", affiliatePrimaryLabel: "Mind Lab Pro",
    affiliateSecondary: "https://nootropicsdepot.com/phosphatidylserine-capsules/?rfsn=supplement-stacker", affiliateSecondaryLabel: "Nootropics Depot",
    affiliateAmazon: "https://www.amazon.com/s?k=phosphatidylserine+supplement&tag=nootropicstk-20",
    safetyRating: "very_safe" as const, isPopular: true, isFeatured: false,
  },
  {
    slug: "rhodiola",
    name: "Rhodiola Rosea",
    category: "Adaptogen",
    summary: "A powerful adaptogenic herb that combats mental fatigue, improves stress resilience, and boosts physical and cognitive performance under pressure.",
    description: "Rhodiola rosea is a Scandinavian and Siberian adaptogen with centuries of use in traditional medicine. Its active compounds, rosavins and salidroside, modulate the stress response system (HPA axis) to reduce the impact of physical and mental stressors. Research shows it significantly reduces fatigue and burnout, improves cognitive function under stress, and enhances mood. It is particularly effective for students, executives, and athletes who face high-pressure performance demands.",
    dosageMin: 200, dosageMax: 600, dosageUnit: "mg",
    scoreEnergy: 7, scoreMood: 8, scoreMemory: 5, scoreFocus: 7, scoreCreativity: 6, scoreSleep: 3, scoreAnxiety: 7,
    affiliatePrimary: "https://nootropicsdepot.com/rhodiola-rosea-capsules/?rfsn=supplement-stacker", affiliatePrimaryLabel: "Nootropics Depot",
    affiliateSecondary: "https://www.iherb.com/c/rhodiola-rosea?rcode=NSTACKER", affiliateSecondaryLabel: "iHerb",
    affiliateAmazon: "https://www.amazon.com/s?k=rhodiola+rosea+supplement&tag=nootropicstk-20",
    safetyRating: "very_safe" as const, isPopular: true, isFeatured: true,
  },
  {
    slug: "ashwagandha",
    name: "Ashwagandha (KSM-66)",
    category: "Adaptogen",
    summary: "The gold-standard adaptogen for stress and anxiety reduction, with KSM-66 being the most clinically studied extract for cortisol management.",
    description: "Ashwagandha (Withania somnifera) is an ancient Ayurvedic herb classified as an adaptogen. KSM-66 is the most concentrated, full-spectrum root extract available, with the largest body of clinical research. Studies confirm it significantly reduces cortisol levels, anxiety, and stress. It also improves sleep quality, testosterone levels in men, and cognitive function. It is one of the most universally recommended supplements for anyone dealing with chronic stress or anxiety.",
    dosageMin: 300, dosageMax: 600, dosageUnit: "mg",
    scoreEnergy: 5, scoreMood: 8, scoreMemory: 5, scoreFocus: 5, scoreCreativity: 4, scoreSleep: 8, scoreAnxiety: 9,
    affiliatePrimary: "https://neurohacker.com/shop/qualia-resilience?rfsn=supplement-stacker", affiliatePrimaryLabel: "Neurohacker",
    affiliateSecondary: "https://www.iherb.com/c/ashwagandha?rcode=NSTACKER", affiliateSecondaryLabel: "iHerb",
    affiliateAmazon: "https://www.amazon.com/s?k=ashwagandha+ksm-66&tag=nootropicstk-20",
    safetyRating: "very_safe" as const, isPopular: true, isFeatured: true,
  },
  {
    slug: "magnesium",
    name: "Magnesium L-Threonate",
    category: "Mineral",
    summary: "The only form of magnesium clinically shown to cross the blood-brain barrier, directly increasing synaptic density and improving memory and sleep.",
    description: "Magnesium L-Threonate (MgT) was developed by MIT researchers specifically to increase brain magnesium levels. Unlike other magnesium forms, it efficiently crosses the blood-brain barrier. Clinical studies show it increases synaptic density in the hippocampus, improving short-term and long-term memory, learning, and cognitive flexibility. It also significantly improves sleep quality by promoting deeper, more restorative sleep. It is a foundational supplement for anyone over 30 concerned about cognitive aging.",
    dosageMin: 1500, dosageMax: 2000, dosageUnit: "mg",
    scoreEnergy: 3, scoreMood: 6, scoreMemory: 8, scoreFocus: 6, scoreCreativity: 5, scoreSleep: 9, scoreAnxiety: 7,
    affiliatePrimary: "https://www.thorne.com/products/dp/magnesium-bisglycinate?ref=nootropicstacker", affiliatePrimaryLabel: "Thorne",
    affiliateSecondary: "https://nootropicsdepot.com/magnesium-l-threonate-capsules/?rfsn=supplement-stacker", affiliateSecondaryLabel: "Nootropics Depot",
    affiliateAmazon: "https://www.amazon.com/s?k=magnesium+l-threonate&tag=nootropicstk-20",
    safetyRating: "very_safe" as const, isPopular: true, isFeatured: true,
  },
  {
    slug: "n-acetyl-l-tyrosine",
    name: "N-Acetyl L-Tyrosine (NALT)",
    category: "Amino Acid",
    summary: "A highly bioavailable form of tyrosine that replenishes dopamine and norepinephrine under stress, maintaining focus and motivation when depleted.",
    description: "N-Acetyl L-Tyrosine (NALT) is an acetylated form of the amino acid L-Tyrosine, offering superior bioavailability. Tyrosine is the direct precursor to the catecholamine neurotransmitters dopamine, norepinephrine, and epinephrine. Under conditions of stress, sleep deprivation, or intense cognitive demand, these neurotransmitters become depleted. NALT replenishes them, maintaining cognitive performance and motivation when you need it most. It is particularly effective for high-stress situations and works synergistically with stimulants.",
    dosageMin: 300, dosageMax: 600, dosageUnit: "mg",
    scoreEnergy: 7, scoreMood: 7, scoreMemory: 5, scoreFocus: 8, scoreCreativity: 6, scoreSleep: 1, scoreAnxiety: 3,
    affiliatePrimary: "https://nootropicsdepot.com/n-acetyl-l-tyrosine-capsules/?rfsn=supplement-stacker", affiliatePrimaryLabel: "Nootropics Depot",
    affiliateSecondary: "https://www.iherb.com/c/l-tyrosine?rcode=NSTACKER", affiliateSecondaryLabel: "iHerb",
    affiliateAmazon: "https://www.amazon.com/s?k=n-acetyl+l-tyrosine+nalt&tag=nootropicstk-20",
    safetyRating: "safe" as const, isPopular: false, isFeatured: false,
  },
  {
    slug: "panax-ginseng",
    name: "Panax Ginseng",
    category: "Adaptogen",
    summary: "One of the most researched adaptogens in the world, improving mental performance, energy, immune function, and reducing fatigue.",
    description: "Panax ginseng (Korean ginseng) has been used in traditional Chinese medicine for over 2,000 years. Its active compounds, ginsenosides, have been shown in numerous clinical trials to improve working memory, reaction time, and mental arithmetic. It reduces fatigue, supports immune function, and has anti-inflammatory properties. It is one of the few herbal nootropics with a robust enough evidence base to be included in premium formulations like Mind Lab Pro.",
    dosageMin: 200, dosageMax: 400, dosageUnit: "mg",
    scoreEnergy: 7, scoreMood: 6, scoreMemory: 7, scoreFocus: 7, scoreCreativity: 5, scoreSleep: 2, scoreAnxiety: 4,
    affiliatePrimary: "https://www.mindlabpro.com/?a_aid=nootropicstacker", affiliatePrimaryLabel: "Mind Lab Pro",
    affiliateSecondary: "https://www.iherb.com/c/panax-ginseng?rcode=NSTACKER", affiliateSecondaryLabel: "iHerb",
    affiliateAmazon: "https://www.amazon.com/s?k=panax+ginseng+supplement&tag=nootropicstk-20",
    safetyRating: "safe" as const, isPopular: false, isFeatured: false,
  },
  {
    slug: "pine-bark-extract",
    name: "Maritime Pine Bark Extract",
    category: "Antioxidant",
    summary: "A powerful antioxidant complex that boosts cerebral blood flow and protects neurons from oxidative damage, with strong clinical evidence.",
    description: "Maritime Pine Bark Extract (standardized to 95% proanthocyanidins) is one of the most potent antioxidant complexes in nature. It works by increasing nitric oxide production, which dilates blood vessels and improves cerebral blood flow. This delivers more oxygen and glucose to the brain, enhancing mental energy and focus. It also crosses the blood-brain barrier to directly protect neurons from free radical damage. It is a key ingredient in Mind Lab Pro and is particularly valuable for older adults.",
    dosageMin: 75, dosageMax: 150, dosageUnit: "mg",
    scoreEnergy: 5, scoreMood: 5, scoreMemory: 7, scoreFocus: 7, scoreCreativity: 4, scoreSleep: 3, scoreAnxiety: 4,
    affiliatePrimary: "https://www.mindlabpro.com/?a_aid=nootropicstacker", affiliatePrimaryLabel: "Mind Lab Pro",
    affiliateSecondary: "https://nootropicsdepot.com/pycnogenol-capsules/?rfsn=supplement-stacker", affiliateSecondaryLabel: "Nootropics Depot",
    affiliateAmazon: "https://www.amazon.com/s?k=pine+bark+extract+pycnogenol&tag=nootropicstk-20",
    safetyRating: "very_safe" as const, isPopular: false, isFeatured: false,
  },
  {
    slug: "vitamin-b6",
    name: "Vitamin B6 (P-5-P)",
    category: "Vitamin",
    summary: "An essential cofactor for neurotransmitter synthesis (dopamine, serotonin, GABA), making it a critical foundation for any cognitive or mood stack.",
    description: "Vitamin B6 in its active form, Pyridoxal-5-Phosphate (P-5-P), is an essential cofactor in the synthesis of multiple key neurotransmitters including dopamine, serotonin, GABA, and norepinephrine. Deficiency is surprisingly common and linked to depression, anxiety, brain fog, and poor sleep. Supplementing with P-5-P ensures your brain has the raw materials needed to produce mood-regulating and focus-enhancing neurotransmitters. It is a foundational supplement that amplifies the effects of many other nootropics.",
    dosageMin: 2.5, dosageMax: 25, dosageUnit: "mg",
    scoreEnergy: 4, scoreMood: 7, scoreMemory: 5, scoreFocus: 5, scoreCreativity: 4, scoreSleep: 5, scoreAnxiety: 6,
    affiliatePrimary: "https://www.thorne.com/products/dp/b-complex-plus?ref=nootropicstacker", affiliatePrimaryLabel: "Thorne",
    affiliateSecondary: "https://www.iherb.com/c/vitamin-b6?rcode=NSTACKER", affiliateSecondaryLabel: "iHerb",
    affiliateAmazon: "https://www.amazon.com/s?k=vitamin+b6+p5p+supplement&tag=nootropicstk-20",
    safetyRating: "very_safe" as const, isPopular: false, isFeatured: false,
  },
  {
    slug: "vitamin-b12",
    name: "Vitamin B12 (Methylcobalamin)",
    category: "Vitamin",
    summary: "Essential for myelin sheath integrity and neurological function; methylcobalamin is the most bioavailable form for brain health.",
    description: "Vitamin B12 (as methylcobalamin) is essential for the maintenance of the myelin sheath that insulates nerve fibers, enabling fast and efficient neural signaling. Deficiency — common in vegans, vegetarians, and older adults — causes cognitive decline, fatigue, depression, and neurological damage. Methylcobalamin is the most bioavailable and neurologically active form. Supplementation supports mental energy, mood, and long-term neuroprotection.",
    dosageMin: 500, dosageMax: 1000, dosageUnit: "mcg",
    scoreEnergy: 6, scoreMood: 6, scoreMemory: 5, scoreFocus: 5, scoreCreativity: 3, scoreSleep: 3, scoreAnxiety: 4,
    affiliatePrimary: "https://www.thorne.com/products/dp/b12?ref=nootropicstacker", affiliatePrimaryLabel: "Thorne",
    affiliateSecondary: "https://www.iherb.com/c/vitamin-b12?rcode=NSTACKER", affiliateSecondaryLabel: "iHerb",
    affiliateAmazon: "https://www.amazon.com/s?k=vitamin+b12+methylcobalamin&tag=nootropicstk-20",
    safetyRating: "very_safe" as const, isPopular: false, isFeatured: false,
  },
  {
    slug: "omega-3",
    name: "Omega-3 (DHA/EPA)",
    category: "Essential Fatty Acid",
    summary: "DHA is the primary structural fat in the brain; omega-3 supplementation supports neuroplasticity, mood, and long-term cognitive health.",
    description: "Docosahexaenoic acid (DHA) constitutes approximately 97% of the omega-3 fatty acids in the brain and is a primary structural component of neuronal cell membranes. Adequate DHA is essential for neuroplasticity, synaptic transmission, and neuroprotection. EPA (eicosapentaenoic acid) has potent anti-inflammatory effects that protect the brain from chronic inflammation. Clinical research links omega-3 supplementation with improved mood, reduced depression, better memory, and protection against age-related cognitive decline.",
    dosageMin: 1000, dosageMax: 3000, dosageUnit: "mg",
    scoreEnergy: 3, scoreMood: 7, scoreMemory: 7, scoreFocus: 6, scoreCreativity: 5, scoreSleep: 5, scoreAnxiety: 6,
    affiliatePrimary: "https://www.thorne.com/products/dp/super-epa?ref=nootropicstacker", affiliatePrimaryLabel: "Thorne",
    affiliateSecondary: "https://www.iherb.com/c/fish-oil?rcode=NSTACKER", affiliateSecondaryLabel: "iHerb",
    affiliateAmazon: "https://www.amazon.com/s?k=omega+3+fish+oil+dha+epa&tag=nootropicstk-20",
    safetyRating: "very_safe" as const, isPopular: true, isFeatured: false,
  },
  {
    slug: "caffeine",
    name: "Caffeine",
    category: "Stimulant",
    summary: "The world's most widely used psychoactive substance, blocking adenosine receptors to increase alertness and energy. Best paired with L-Theanine.",
    description: "Caffeine is an adenosine receptor antagonist that prevents the buildup of the sleep-promoting chemical adenosine, resulting in increased alertness, reduced fatigue, and enhanced physical and cognitive performance. It is the most studied psychoactive substance in the world with an unparalleled safety record at moderate doses. The classic 1:2 caffeine-to-L-Theanine stack is one of the most effective and well-researched nootropic combinations, delivering clean, focused energy without jitteriness.",
    dosageMin: 100, dosageMax: 200, dosageUnit: "mg",
    scoreEnergy: 10, scoreMood: 6, scoreMemory: 5, scoreFocus: 9, scoreCreativity: 5, scoreSleep: 0, scoreAnxiety: 1,
    affiliatePrimary: "https://nootropicsdepot.com/caffeine-capsules/?rfsn=supplement-stacker", affiliatePrimaryLabel: "Nootropics Depot",
    affiliateSecondary: "https://www.iherb.com/c/caffeine?rcode=NSTACKER", affiliateSecondaryLabel: "iHerb",
    affiliateAmazon: "https://www.amazon.com/s?k=caffeine+200mg+capsules&tag=nootropicstk-20",
    safetyRating: "safe" as const, isPopular: true, isFeatured: false,
  },
  {
    slug: "creatine-monohydrate",
    name: "Creatine Monohydrate",
    category: "Energy Substrate",
    summary: "Beyond muscle building, creatine fuels the brain's ATP energy system, improving working memory, reasoning, and mental endurance.",
    description: "Creatine monohydrate is best known as a muscle-building supplement, but its cognitive benefits are equally impressive. The brain is an energy-hungry organ that relies on ATP for all cognitive functions. Creatine increases the brain's phosphocreatine stores, enabling faster ATP regeneration during periods of intense cognitive demand. Meta-analyses confirm it improves working memory, reasoning, and intelligence test scores, particularly in sleep-deprived individuals and vegetarians (who have lower baseline brain creatine).",
    dosageMin: 3000, dosageMax: 5000, dosageUnit: "mg",
    scoreEnergy: 7, scoreMood: 5, scoreMemory: 7, scoreFocus: 6, scoreCreativity: 4, scoreSleep: 3, scoreAnxiety: 3,
    affiliatePrimary: "https://www.onnit.com/creatine/?a_aid=nootropicstacker", affiliatePrimaryLabel: "Onnit",
    affiliateSecondary: "https://www.iherb.com/c/creatine?rcode=NSTACKER", affiliateSecondaryLabel: "iHerb",
    affiliateAmazon: "https://www.amazon.com/s?k=creatine+monohydrate&tag=nootropicstk-20",
    safetyRating: "very_safe" as const, isPopular: true, isFeatured: false,
  },
  {
    slug: "qualia-mind",
    name: "Qualia Mind (Full Stack)",
    category: "Pre-formulated Stack",
    summary: "Neurohacker Collective's flagship all-in-one nootropic stack with 28 premium ingredients for comprehensive cognitive enhancement.",
    description: "Qualia Mind by Neurohacker Collective is one of the most comprehensive and premium pre-formulated nootropic stacks available. It contains 28 carefully selected ingredients including Citicoline, Phosphatidylserine, Bacopa, Rhodiola, Lion's Mane, and multiple vitamins and amino acids. Neurohacker uses a systems biology approach to formulation, ensuring ingredients work synergistically. It is designed to support focus, memory, mental clarity, creativity, and long-term brain health. At ~$139/bottle, it targets serious biohackers willing to invest in premium quality.",
    dosageMin: 7, dosageMax: 7, dosageUnit: "capsules",
    scoreEnergy: 8, scoreMood: 8, scoreMemory: 9, scoreFocus: 9, scoreCreativity: 8, scoreSleep: 4, scoreAnxiety: 6,
    affiliatePrimary: "https://neurohacker.com/shop/qualia-mind?rfsn=supplement-stacker", affiliatePrimaryLabel: "Neurohacker (15% off)",
    affiliateSecondary: null, affiliateSecondaryLabel: null,
    affiliateAmazon: "https://www.amazon.com/s?k=qualia+mind+neurohacker&tag=nootropicstk-20",
    safetyRating: "safe" as const, isPopular: true, isFeatured: true,
  },
  {
    slug: "mind-lab-pro",
    name: "Mind Lab Pro",
    category: "Pre-formulated Stack",
    summary: "The world's most popular all-in-one nootropic with 11 research-backed ingredients targeting all aspects of brain health and performance.",
    description: "Mind Lab Pro is formulated by Opti-Nutra and contains 11 evidence-backed ingredients: Citicoline, Phosphatidylserine, Bacopa Monnieri, Lion's Mane, Maritime Pine Bark, L-Tyrosine, L-Theanine, Rhodiola Rosea, and B vitamins. It uses premium, patented forms of each ingredient and is manufactured to pharmaceutical standards. It is the best-selling nootropic stack in the world and is appropriate for students, professionals, and athletes. Its 30-day money-back guarantee makes it a low-risk entry point for nootropic beginners.",
    dosageMin: 4, dosageMax: 4, dosageUnit: "capsules",
    scoreEnergy: 7, scoreMood: 8, scoreMemory: 9, scoreFocus: 9, scoreCreativity: 7, scoreSleep: 4, scoreAnxiety: 7,
    affiliatePrimary: "https://www.mindlabpro.com/?a_aid=nootropicstacker", affiliatePrimaryLabel: "Mind Lab Pro (Official)",
    affiliateSecondary: null, affiliateSecondaryLabel: null,
    affiliateAmazon: "https://www.amazon.com/s?k=mind+lab+pro&tag=nootropicstk-20",
    safetyRating: "very_safe" as const, isPopular: true, isFeatured: true,
  },
  {
    slug: "ginkgo-biloba",
    name: "Ginkgo Biloba",
    category: "Herbal",
    summary: "One of the oldest medicinal herbs, improving cerebral blood flow, memory, and processing speed with decades of clinical research.",
    description: "Ginkgo biloba extract (standardized to 24% flavonol glycosides and 6% terpene lactones) is derived from the oldest living tree species on Earth. It works primarily by increasing cerebral blood flow and acting as a powerful antioxidant. Dozens of clinical trials support its ability to improve memory, processing speed, and attention, particularly in older adults. It is one of the most widely used herbal supplements in Europe, where it is prescribed for cognitive decline and dementia.",
    dosageMin: 120, dosageMax: 240, dosageUnit: "mg",
    scoreEnergy: 4, scoreMood: 5, scoreMemory: 8, scoreFocus: 7, scoreCreativity: 4, scoreSleep: 3, scoreAnxiety: 4,
    affiliatePrimary: "https://nootropicsdepot.com/ginkgo-biloba-capsules/?rfsn=supplement-stacker", affiliatePrimaryLabel: "Nootropics Depot",
    affiliateSecondary: "https://www.iherb.com/c/ginkgo-biloba?rcode=NSTACKER", affiliateSecondaryLabel: "iHerb",
    affiliateAmazon: "https://www.amazon.com/s?k=ginkgo+biloba+supplement&tag=nootropicstk-20",
    safetyRating: "safe" as const, isPopular: false, isFeatured: false,
  },
  {
    slug: "melatonin",
    name: "Melatonin",
    category: "Sleep",
    summary: "The body's primary sleep hormone; low-dose supplementation helps regulate circadian rhythm and improve sleep onset without grogginess.",
    description: "Melatonin is a hormone produced by the pineal gland that regulates the sleep-wake cycle. Supplementation is most effective at low doses (0.5–1mg) for resetting circadian rhythm and improving sleep onset latency. Higher doses (3–10mg) are often used but may cause grogginess. Adequate sleep is foundational to cognitive performance — melatonin is therefore an indirect but powerful nootropic. It also has antioxidant properties and may offer neuroprotective benefits.",
    dosageMin: 0.5, dosageMax: 3, dosageUnit: "mg",
    scoreEnergy: 1, scoreMood: 5, scoreMemory: 4, scoreFocus: 2, scoreCreativity: 2, scoreSleep: 10, scoreAnxiety: 5,
    affiliatePrimary: "https://www.iherb.com/c/melatonin?rcode=NSTACKER", affiliatePrimaryLabel: "iHerb",
    affiliateSecondary: "https://www.thorne.com/products/dp/melaton-3?ref=nootropicstacker", affiliateSecondaryLabel: "Thorne",
    affiliateAmazon: "https://www.amazon.com/s?k=melatonin+0.5mg+low+dose&tag=nootropicstk-20",
    safetyRating: "safe" as const, isPopular: true, isFeatured: false,
  },
  {
    slug: "vitamin-d3",
    name: "Vitamin D3 + K2",
    category: "Vitamin",
    summary: "Vitamin D3 acts as a neurosteroid, supporting mood, cognition, and immune function; K2 ensures proper calcium metabolism.",
    description: "Vitamin D3 (cholecalciferol) is technically a hormone that acts on receptors throughout the brain and body. Deficiency — affecting an estimated 40% of Americans — is strongly associated with depression, cognitive impairment, and increased risk of neurodegenerative disease. Supplementation improves mood, cognitive function, immune response, and bone health. Vitamin K2 (MK-7) is paired with D3 to direct calcium to bones rather than arteries, making the combination safer and more effective.",
    dosageMin: 2000, dosageMax: 5000, dosageUnit: "IU",
    scoreEnergy: 5, scoreMood: 7, scoreMemory: 5, scoreFocus: 5, scoreCreativity: 3, scoreSleep: 5, scoreAnxiety: 5,
    affiliatePrimary: "https://www.thorne.com/products/dp/vitamin-d-k2?ref=nootropicstacker", affiliatePrimaryLabel: "Thorne",
    affiliateSecondary: "https://www.iherb.com/c/vitamin-d3?rcode=NSTACKER", affiliateSecondaryLabel: "iHerb",
    affiliateAmazon: "https://www.amazon.com/s?k=vitamin+d3+k2+supplement&tag=nootropicstk-20",
    safetyRating: "very_safe" as const, isPopular: true, isFeatured: false,
  },
  {
    slug: "noopept",
    name: "Noopept",
    category: "Racetam-like",
    summary: "A potent synthetic peptide nootropic with effects similar to piracetam but at 1000x lower doses, enhancing memory, focus, and BDNF.",
    description: "Noopept is a synthetic nootropic peptide developed in Russia that is structurally related to the racetam family but far more potent. At doses of just 10–30mg, it enhances memory consolidation, learning, and focus. It increases the expression of BDNF (Brain-Derived Neurotrophic Factor) and NGF, supporting neuroplasticity. It also has neuroprotective and anxiolytic properties. Noopept is popular among experienced biohackers and is best cycled to maintain effectiveness.",
    dosageMin: 10, dosageMax: 30, dosageUnit: "mg",
    scoreEnergy: 5, scoreMood: 6, scoreMemory: 9, scoreFocus: 8, scoreCreativity: 7, scoreSleep: 2, scoreAnxiety: 5,
    affiliatePrimary: "https://nootropicsdepot.com/noopept-capsules/?rfsn=supplement-stacker", affiliatePrimaryLabel: "Nootropics Depot",
    affiliateSecondary: null, affiliateSecondaryLabel: null,
    affiliateAmazon: "https://www.amazon.com/s?k=noopept+nootropic&tag=nootropicstk-20",
    safetyRating: "moderate" as const, isPopular: false, isFeatured: false,
  },
  {
    slug: "ag1-athletic-greens",
    name: "AG1 (Athletic Greens)",
    category: "Pre-formulated Stack",
    summary: "A comprehensive daily foundational nutrition supplement with 75 vitamins, minerals, and whole food ingredients for overall health and energy.",
    description: "AG1 by Athletic Greens is a comprehensive all-in-one daily nutrition supplement containing 75 high-quality vitamins, minerals, whole food-sourced nutrients, probiotics, and adaptogens. While not a targeted nootropic stack, it provides the nutritional foundation that supports optimal brain function. It covers common deficiencies (B vitamins, Vitamin D, magnesium, zinc) that impair cognitive performance. It is ideal as a foundational supplement to pair with more targeted nootropics.",
    dosageMin: 12, dosageMax: 12, dosageUnit: "g (1 scoop)",
    scoreEnergy: 7, scoreMood: 6, scoreMemory: 4, scoreFocus: 5, scoreCreativity: 3, scoreSleep: 4, scoreAnxiety: 5,
    affiliatePrimary: "https://athleticgreens.com/r/nootropicstacker", affiliatePrimaryLabel: "AG1 (Free Gift)",
    affiliateSecondary: null, affiliateSecondaryLabel: null,
    affiliateAmazon: null,
    safetyRating: "very_safe" as const, isPopular: true, isFeatured: true,
  },
];

async function seed() {
  console.log("Seeding supplements...");
  for (const supp of supplementData) {
    await db.insert(supplements).values(supp).onDuplicateKeyUpdate({
      set: {
        name: supp.name,
        category: supp.category,
        summary: supp.summary,
        description: supp.description,
        dosageMin: supp.dosageMin,
        dosageMax: supp.dosageMax,
        dosageUnit: supp.dosageUnit,
        scoreEnergy: supp.scoreEnergy,
        scoreMood: supp.scoreMood,
        scoreMemory: supp.scoreMemory,
        scoreFocus: supp.scoreFocus,
        scoreCreativity: supp.scoreCreativity,
        scoreSleep: supp.scoreSleep,
        scoreAnxiety: supp.scoreAnxiety,
        affiliatePrimary: supp.affiliatePrimary,
        affiliatePrimaryLabel: supp.affiliatePrimaryLabel,
        affiliateSecondary: supp.affiliateSecondary,
        affiliateSecondaryLabel: supp.affiliateSecondaryLabel,
        affiliateAmazon: supp.affiliateAmazon,
        safetyRating: supp.safetyRating,
        isPopular: supp.isPopular,
        isFeatured: supp.isFeatured,
      },
    });
  }
  console.log(`✅ Seeded ${supplementData.length} supplements (all fields updated)`);
  process.exit(0);
}

seed().catch((e) => { console.error(e); process.exit(1); });
